#server.port=9090
spring.application.name=veebipood
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-dahd0r6q1p3s73eeh1mg-a.frankfurt-postgres.render.com/veebipood_vscl
spring.datasource.username=veebipood_vscl_user
spring.datasource.password=sNQqS37AUz4pSS0JyFKNQxSrTv6Op8xx


logging.file.name=logging.log